name: Hello World Workflows
on: 
    push:
        branches:
            - main
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World"

            - name: "Check PWD"
              run: pwd
            
            - name: "Check WHOAMI"
              run: whoami

            - name: "cat /etc/os-release"
              run: cat /etc/os-release

            - name: "mkdir abc"
              run: mkdir abc

            - name: "ls -al /"
              run: ls -al

